Controllers/BoardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using System.IO;

using HompPage.Models;
using System.Data.Entity;

namespace HompPage.Controllers
{
    public class BoardController : Controller
    {
        // GET: Board
        HomePageEntities2 db = new HomePageEntities2();

        //뷰에 디비 값을 전달 한다.
        [HttpGet]
        public ActionResult Create()
        {
            Articles article = new Articles();
            return View(article);
        }

        [HttpPost]
        public ActionResult Create(Articles article)
        {
            
            try
            {
                article.ViewCnt = 0;
                article.IPAddress = Request.ServerVariables["REMOTE_ADDR"].ToString();
                article.RegistDate = DateTime.Now;
                article.RegistUserName = "admin";
                article.ModifyDate = DateTime.Now;
                article.ModifyUserName = "admin";

                db.Articles.Add(article);
                db.SaveChanges();

                if (Request.Files.Count > 0)
                {
                    var attachFile = Request.Files[0];

                    if (attachFile != null && attachFile.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(attachFile.FileName);
                        var path = Path.Combine(Server.MapPath("~/Upload/"), fileName);
                        attachFile.SaveAs(path);

                        ArticleFiles file = new ArticleFiles();

                        file.ArticleIDX = article.ArticleIDX;
                        file.FilePath = "/Upload/";
                        file.FileName = fileName;
                        file.FileFormat = Path.GetExtension(attachFile.FileName);
                        file.FileSize = attachFile.ContentLength;
                        file.UploadDate = DateTime.Now;
                        db.ArticleFiles.Add(file);
                        db.SaveChanges();
                    }
                    ViewBag.Result = "OK";
                }
            }
            catch (Exception ex)
            {
                ViewBag.Result = "FAIL";
            }
            return View(article);
        }


        [HttpGet]
        public ActionResult ArticleList()
        {
            try
            {
                List<Articles> list = db.Articles.OrderByDescending(o => o.ModifyDate).ToList();
                return View(list);
            }
            catch (Exception ex)
            {

            }
            return View();

        }

        [HttpGet]
        public ActionResult Edit(int aidx)
        {
            ArticleEditViewModel vm = new ArticleEditViewModel();

            Articles article = db.Articles.Where(c => c.ArticleIDX == aidx).FirstOrDefault();

            List<ArticleFiles> files = db.ArticleFiles.Where(c => c.ArticleIDX == aidx).OrderBy(o => o.UploadDate).ToList();
            vm.Article = article;
            vm.Files = files;

            return View(vm);
        }

        [HttpPost]
        public ActionResult Edit(ArticleEditViewModel vm)
        {
            ArticleEditViewModel dbVM = new ArticleEditViewModel();

            try
            {
                Articles dbArticle = db.Articles.Find(vm.Article.ArticleIDX);

                dbArticle.Title = vm.Article.Title;
                dbArticle.ArticleType = vm.Article.ArticleType;
                dbArticle.Contents = vm.Article.Contents;
                dbArticle.IPAddress = Request.ServerVariables["REMOTE_ADDR"].ToString();
                dbArticle.ModifyDate = DateTime.Now;
                dbArticle.ModifyUserName = "admin";

                db.Entry(dbArticle).State = EntityState.Modified;
                db.SaveChanges();

             

                if(Request.Files.Count > 0)
                {
                    var attachFile = Request.Files[0];                  

                    if (attachFile != null && attachFile.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(attachFile.FileName);
                        var path = Path.Combine(Server.MapPath("~/Upload"), fileName);
                        
                        attachFile.SaveAs(path);

                        ArticleFiles file = new ArticleFiles();
                        file.ArticleIDX = vm.Article.ArticleIDX;
                        file.FilePath = "/Upload/";
                        file.FileName = fileName;
                        file.FileFormat = Path.GetExtension(attachFile.FileName);
                        file.FileSize = attachFile.ContentLength;
                        file.UploadDate = DateTime.Now;
                       

                        db.ArticleFiles.Add(file);
                        db.SaveChanges();
                    }
                }
                Articles article = db.Articles.Where(c => c.ArticleIDX == vm.Article.ArticleIDX).FirstOrDefault();
                List<ArticleFiles> files = db.ArticleFiles.Where(c => c.ArticleIDX == vm.Article.ArticleIDX).OrderBy(o => o.UploadDate).ToList();

                dbVM.Article = article;
                dbVM.Files = files;
                ViewBag.Result = "OK";
            }
            catch (Exception ex)
            {
                dbVM = vm;
                ViewBag.Result = "FAIL";
            }
            return View(dbVM);
        }

        [HttpGet]
        public ActionResult ArticleDelete(int aidx)
        {
            Articles dbArticle = db.Articles.Where(c => c.ArticleIDX == aidx).FirstOrDefault();
            db.Articles.Remove(dbArticle);
            db.SaveChanges();

            return RedirectToAction("ArticleList");
        }

        [HttpGet]
        public ActionResult FileRemove(int fidx)
        {
            ArticleFiles file = db.ArticleFiles.Where(c => c.FileIDX == fidx).FirstOrDefault();
            int articleIDX = Convert.ToInt32(file.ArticleIDX);

            System.IO.File.Delete(Server.MapPath(file.FilePath + file.FileName));

            db.ArticleFiles.Remove(file);
            db.SaveChanges();

            return RedirectToAction("Edit", new { aidx = articleIDX.ToString() });
        }
    }
}

Views/Board/ArticleList.cshtml
@using HompPage.Models;

@model List<HompPage.Models.Articles>

@{
    ViewBag.Title = "ArticleList";
    Layout = "~/Views/Shared/_HomePageLayoutPage.cshtml";
}

<div class="content-wrap">
    <div id="blogpost" class="inner-content">
        <section class="inner-section">
            <div class="container-fluid nopadding">
                <div class="wow fadeInDown" data-wow-delay="0.6s" data-wow-offset="10">
                    <div id="post-comment">
                        <h4 class="font-accident-one-light uppercase">게시글 목록</h4>
                    </div>
                    <div class="dividewhite2"></div>

                    <div class="row">                       
                        <table  class="footable table table-striped toggle-arrow-tiny"data-pageing-size="10">
                            <thead>
                                <tr>
                                    <th data-toggle="true" data-sort-ignore="true" width="5%">순번</th>
                                    @*<th data-toggle="true" data-sort-ignore="true" width="5%">글 아이디</th>*@
                                    <th data-sort-ignore="true" width="5%">종류</th>
                                    <th data-hide="phone,tablet"  width="10%">제목</th>
                                    <th data-toggle="true" data-sort-ignore="true" width="30%">내용</th>
                                    <th data-toggle="true" class="text-center" width="10%">작성일</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{
                                    int i = 0;
                                    int idx = 0;
                                }
                                @foreach (var item in Model)
                                {
                                    idx = Model.Count - i;
                                    <tr>
                                        <td>@idx</td>
                                        @*<td><a href="/Board/Edit?aidx=@item.ArticleIDX">@item.ArticleIDX</a></td>*@
                                        <td>@item.ArticleType</td>
                                        <td><a href="/Board/Edit?aidx=@item.ArticleIDX">@item.Title</a></td>
                                        <td>@item.Contents</td>
                                        <td>@item.ModifyDate</td>
                                    </tr>
                                    i++;
                                }
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="6"><ul class="pagination pull-right" ></ul>
                                   
                                    </td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>

                </div>
            </div>
            <div class="dividewhite8"></div>
        </section>
    </div>
</div>


@section Scripts{
    <script> 
        $(document).ready(function () {
            $('.footable').footable();
        });

       
    </script>
    }

Views/Board/Create.cshtml
@using HompPage.Models;

@model HompPage.Models.Articles

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_HomePageLayoutPage.cshtml";
}

<div id="bologpost" class="inner-content">
    <section id="page-title" class="inner-section">
        <div class="container-fluid nopadding cd-words-wrapper fadeInRight" data-wow-delay="0.4s" data-wow-offset="10" style="height:40px">
            <h2 class="font-accident-one-normal uppercase">관리자 모드</h2>
        </div>
    </section>

    <section class="inner-section color01">
        <div class="container-fluid nopadding">
            <div class="cd-words-wrapper fadeInDown" data-wow-delay="0.6s" data-wow-offset="10">
                <div id="post-comment">
                    <h4 class="font-accident-one-light uppercase">게시글 쓰기</h4>
                </div>

                <div class="dividewhite2"></div>


                <form id="formdata" action="@Url.Action("Create" , "Board")" method="post" enctype="multipart/form-data">
                    <div class="row">
                        <div class="col-md-12">
                            <p>
                                <label>제목</label>
                                @Html.TextBoxFor(m => m.Title, new { placeholder = "제목을 입력하세요." })
                            </p>

                        </div>
                        <div class="col-md-12">
                            <label>분류</label>
                        </div>

                        <div class="col-md-12">
                            <p>
                                @Html.DropDownListFor(m => m.ArticleType, new SelectList(new List<Object> {
                           new{ value="" , text="선택"},
                            new{ value="C#" , text="C#"},
                             new{ value="Java" , text="Java"},
                              new{ value="C++" , text="C++"},
                           }, "value", "text", Model.Contents
                           ), new { style = "width:200px;height:30px;font-size:medium;" })
                            </p>
                        </div>

                        <div class="col-md-12">
                            <p>
                                <label>문의 내용</label>@Html.TextAreaFor(m => m.Contents, new { placeholder = "내용을 입력하세요.", @rows = "10", @cols = "80" })
                            </p>
                        </div>

                        <div class="col-md-12">
                            <p>
                                <label>이미지 첨부</label><input type="file" name="file" id="file" style="border:hidden;" />
                            </p>
                        </div>

                    </div>

                    <div class="dividewhite2"> </div>

                    <p>
                        <button type="submit" id="btnSave" onclick="return fnSaveCheck();" class="btn btn-lg btn-lgr-str">등록하기</button>
                        <a href="/Board/ArticleList" class="btn btn-lg btn-lgr-str">목록이동</a>
                    </p>

                </form>
            </div>
        </div>
        <div class="dividewhite8"> </div>
    </section>

</div>

@section Scripts{
    <script>
        $(document).ready(function () {

            var result = '@ViewBag.Result';

            if (result == 'OK') {
                alert("정상적으로 저장되었습니다.")
            }

            if (result == 'FAIL') {
                alert("저장작업을 실패하였습니다.")
            }
        });

        function fnSaveCheck() {

            if ($("#Title").val() == "") {
                alert("제목을 입력해주십시오.")
                $('#Title').focus();
                return false;
            }
            if ($("#ArticleType").val() == "") {
                alert("분류 정보를 선택해주십시오.")
                $("#ArticleType").focus();
                return false;
            }
            if ($("#Contents").val() == "") {
                alert("내용을 입력해주십시오.")
                $("#Contents").focus();
                return false;
            }
            return true;
        }
    </script>
    }

Views/Board/Edit.cshtml
@using HompPage.Models;

@model HompPage.Models.ArticleEditViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_HomePageLayoutPage.cshtml";
}

<div id="blogpost" class="inner-content">
    <section id="page-title" class="inner-section">
        <div class="container-fluid nopadding wow fadeInRight" data-wow-delay="0.4s" data-wow-offset="10" style="height:40px;">
            <h2 class="font-accident-two-normal uppercase">관리자모드</h2>
        </div>

    </section>
    <form id="formdata" action="@Url.Action("Edit" , "Board")" method="post" enctype="multipart/form-data">
        <section class="inner-section">
            <div class="container-fluid nopadding">
                <div class="wow fadInDown" data-wow-delay="0.6s" data-wow-offset="10">
                    <div id="post-comment">
                        <h4 class="font-accident-one-light uppercase">게시글 쓰기</h4>
                    </div>

                    <div class="dividewhite2"></div>

                    <div class="row">
                        <div class="col-md-12">
                            <p>
                                <label>제목</label>
                                @Html.TextBoxFor(m => m.Article.Title, new { placeholder = "제목을 입력하세요." })
                                @Html.HiddenFor(m => m.Article.ArticleIDX)
                            </p>
                        </div>
                        <div class="col-md-12">
                            <label>분류</label>
                        </div>
                        <div class="col-md-12">
                            <p>
                                @Html.DropDownListFor(m => m.Article.ArticleType, new SelectList(new List<Object> {
                               new{value="" , text="선택"},
                               new{value="C#" , text="C#"},
                               new{value="JAVA" , text="JAVA"},
                               new{value="C++" , text="C++"}
                           }, "value", "text", Model.Article.ArticleType), new { style = "width:200px;height:30px;-font-size:medium;" })
                            </p>
                        </div>
                        <div class="col-md-12">
                            <p>
                                <label>문의내용</label>
                                @Html.TextAreaFor(m => m.Article.Contents, new { placeholder = "내용을 입력하세요", @rows = "10", @cols = "80" })
                            </p>
                        </div>
                        <div class="col-md-12">
                            <p><label>이미지첨부</label><input type="file" name="file" id="file" style="border:hidden;" /></p>
                        </div>
                        <div class="col-md-12">
                            @foreach (var file in Model.Files)
                            {
                                <img src="@file.FilePath@file.FileName" width="100" height="100" onclick="return fnFileDeleteCheck('@file.FileIDX');" />
                            }
                        </div>
                    </div>
                    <div class="dividewhite2"></div>
                    <p>
                        <button type="submit" id="btnSave" onclick="return fnSaveCheck();" class="btn btn-lg btn-lgr-str">저장하기</button>
                        <button type="button" id="btnDelete" onclick="return fnDeleteCheck();" class="btn btn-lg btn-lgr-str">삭제하기</button>
                        <a href="/Board/ArticleList" class="btn btn-lg btn-lgr-str">목록이동</a>
                    </p>
                </div>
            </div>
            <div class="dividewhite8"></div>
        </section>
    </form>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {

            var result = '@ViewBag.Result';
            if (result == 'OK') {
                alert("정상적으로 저장되었습니다.");
            }
            if (result == 'FAIL') {
                alert("저장작업을 실패하였습니다.");
            }
        });

        //저장 유효성 검사
        function fnSaveCheck() {

            if ($("#Article_Title").val() == "") {
                alert("제목을 입력해주십시오.")
                $("#Article_Title").focus();
                return false;
            }

            if ($("#Article_ArticleType").val() == "") {
                alert("분류 정보를 입력해주십시오.")
                $("#Article_ArticleType").focus();
                return false;
            }

            if ($("#Article_Contents").val() == "") {
                alert("분류 정보를 입력해주십시오.")
                $("#Article_Contents").focus();
                return false;
            }
            return true;
        }

        function fnDeleteCheck() {
            if (confirm("게시글을 삭제하시겠습니까?") == true) {
                window.location.href = "/Board/ArticleDelete?aidx=" + $("#Article_ArticleIDX").val();
            } else {
                return false;
            }
        }

        function fnFileDeleteCheck(fidx) {
            if (confirm("이미지를 삭제하시겠습니까?") == true) {
                window.location.href = "/Board/FileRemove?fidx=" + fidx;
            } else {
                return false;
            }
        }
    </script>
    }